version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
      - "javascript"
    open-pull-requests-limit: 10
    allow:
      - dependency-type: "development"
