name: Rename Dependabot Commit Message
on:
  pull_request:
    branches:
      - master
    types:
      - opened
      - synchronize

permissions:
  contents: write
  pull-requests: write

jobs:
  rename-commit:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 2

      - name: Modify commit message
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          LAST_COMMIT_MSG=$(git log -1 --pretty=%B)
          NEW_COMMIT_MSG=$(echo "$LAST_COMMIT_MSG" | sed 's/Bump/bump/g' | sed 's/from//g')
          git config --global user.name "Irfan Shadik Rishad"
          git config --global user.email "77362427+irfanshadikrishad@users.noreply.github.com"
          git commit --amend -m "$NEW_COMMIT_MSG" --no-edit --author "dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>"
          git push --force https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:${{ github.head_ref }}
